<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Assignment extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Assignment_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'assignment/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'assignment/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'assignment/index.html';
            $config['first_url'] = base_url() . 'assignment/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Assignment_model->total_rows($q);
        $assignment = $this->Assignment_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'assignment_data' => $assignment,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('assignment/assignment_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Assignment_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'topic_id' => $row->topic_id,
		'user_id' => $row->user_id,
	    );
            $this->load->view('assignment/assignment_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('assignment'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('assignment/create_action'),
	    'id' => set_value('id'),
	    'topic_id' => set_value('topic_id'),
	    'user_id' => set_value('user_id'),
	);
        $this->load->view('assignment/assignment_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'topic_id' => $this->input->post('topic_id',TRUE),
		'user_id' => $this->input->post('user_id',TRUE),
	    );

            $this->Assignment_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('assignment'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Assignment_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('assignment/update_action'),
		'id' => set_value('id', $row->id),
		'topic_id' => set_value('topic_id', $row->topic_id),
		'user_id' => set_value('user_id', $row->user_id),
	    );
            $this->load->view('assignment/assignment_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('assignment'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'topic_id' => $this->input->post('topic_id',TRUE),
		'user_id' => $this->input->post('user_id',TRUE),
	    );

            $this->Assignment_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('assignment'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Assignment_model->get_by_id($id);

        if ($row) {
            $this->Assignment_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('assignment'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('assignment'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('topic_id', 'topic id', 'trim|required');
	$this->form_validation->set_rules('user_id', 'user id', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Assignment.php */
/* Location: ./application/controllers/Assignment.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-09 23:49:14 */
/* http://harviacode.com */