<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignment extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Assignment_model');
    } 

    /*
     * Listing of assignment
     */
    function index()
    {
        $data['assignment'] = $this->Assignment_model->get_all_assignment();
        
        $data['_view'] = 'assignment/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new assignment
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'topic_id' => $this->input->post('topic_id'),
				'user_id' => $this->input->post('user_id'),
            );
            
            $assignment_id = $this->Assignment_model->add_assignment($params);
            redirect('assignment/index');
        }
        else
        {            
            $data['_view'] = 'assignment/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a assignment
     */
    function edit($id)
    {   
        // check if the assignment exists before trying to edit it
        $data['assignment'] = $this->Assignment_model->get_assignment($id);
        
        if(isset($data['assignment']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'topic_id' => $this->input->post('topic_id'),
					'user_id' => $this->input->post('user_id'),
                );

                $this->Assignment_model->update_assignment($id,$params);            
                redirect('assignment/index');
            }
            else
            {
                $data['_view'] = 'assignment/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The assignment you are trying to edit does not exist.');
    } 

    /*
     * Deleting assignment
     */
    function remove($id)
    {
        $assignment = $this->Assignment_model->get_assignment($id);

        // check if the assignment exists before trying to delete it
        if(isset($assignment['id']))
        {
            $this->Assignment_model->delete_assignment($id);
            redirect('assignment/index');
        }
        else
            show_error('The assignment you are trying to delete does not exist.');
    }
    
}
