<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Migration extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Migration_model');
    } 

    /*
     * Listing of migrations
     */
    function index()
    {
        $data['migrations'] = $this->Migration_model->get_all_migrations();
        
        $data['_view'] = 'migration/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new migration
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'version' => $this->input->post('version'),
            );
            
            $migration_id = $this->Migration_model->add_migration($params);
            redirect('migration/index');
        }
        else
        {            
            $data['_view'] = 'migration/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a migration
     */
    function edit($)
    {   
        // check if the migration exists before trying to edit it
        $data['migration'] = $this->Migration_model->get_migration($);
        
        if(isset($data['migration']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'version' => $this->input->post('version'),
                );

                $this->Migration_model->update_migration($,$params);            
                redirect('migration/index');
            }
            else
            {
                $data['_view'] = 'migration/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The migration you are trying to edit does not exist.');
    } 

    /*
     * Deleting migration
     */
    function remove($)
    {
        $migration = $this->Migration_model->get_migration($);

        // check if the migration exists before trying to delete it
        if(isset($migration['']))
        {
            $this->Migration_model->delete_migration($);
            redirect('migration/index');
        }
        else
            show_error('The migration you are trying to delete does not exist.');
    }
    
}
