<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    } 

    /*
     * Listing of users
     */
    function index()
    {
        $data['users'] = $this->User_model->get_all_users();
        
        $data['_view'] = 'user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password','Password','required|min_length[6]');
		$this->form_validation->set_rules('username','Username','required|min_length[6]');
		$this->form_validation->set_rules('email','Email','required|valid_emails');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'forgotten_password_selector' => $this->input->post('forgotten_password_selector'),
				'forgotten_password_code' => $this->input->post('forgotten_password_code'),
				'forgotten_password_time' => $this->input->post('forgotten_password_time'),
				'ip_address' => $this->input->post('ip_address'),
				'username' => $this->input->post('username'),
				'email' => $this->input->post('email'),
				'activation_selector' => $this->input->post('activation_selector'),
				'activation_code' => $this->input->post('activation_code'),
				'remember_selector' => $this->input->post('remember_selector'),
				'remember_code' => $this->input->post('remember_code'),
				'created_on' => $this->input->post('created_on'),
				'last_login' => $this->input->post('last_login'),
				'active' => $this->input->post('active'),
				'first_name' => $this->input->post('first_name'),
				'last_name' => $this->input->post('last_name'),
				'job_title' => $this->input->post('job_title'),
				'employed_on' => $this->input->post('employed_on'),
				'salary' => $this->input->post('salary'),
				'tasks_completed' => $this->input->post('tasks_completed'),
				'dob' => $this->input->post('dob'),
				'photo' => $this->input->post('photo'),
				'company' => $this->input->post('company'),
				'phone' => $this->input->post('phone'),
				'job_describtion' => $this->input->post('job_describtion'),
            );
            
            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        }
        else
        {            
            $data['_view'] = 'user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user
     */
    function edit($id)
    {   
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($id);
        
        if(isset($data['user']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('password','Password','required|min_length[6]');
			$this->form_validation->set_rules('username','Username','required|min_length[6]');
			$this->form_validation->set_rules('email','Email','required|valid_emails');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'forgotten_password_selector' => $this->input->post('forgotten_password_selector'),
					'forgotten_password_code' => $this->input->post('forgotten_password_code'),
					'forgotten_password_time' => $this->input->post('forgotten_password_time'),
					'ip_address' => $this->input->post('ip_address'),
					'username' => $this->input->post('username'),
					'email' => $this->input->post('email'),
					'activation_selector' => $this->input->post('activation_selector'),
					'activation_code' => $this->input->post('activation_code'),
					'remember_selector' => $this->input->post('remember_selector'),
					'remember_code' => $this->input->post('remember_code'),
					'created_on' => $this->input->post('created_on'),
					'last_login' => $this->input->post('last_login'),
					'active' => $this->input->post('active'),
					'first_name' => $this->input->post('first_name'),
					'last_name' => $this->input->post('last_name'),
					'job_title' => $this->input->post('job_title'),
					'employed_on' => $this->input->post('employed_on'),
					'salary' => $this->input->post('salary'),
					'tasks_completed' => $this->input->post('tasks_completed'),
					'dob' => $this->input->post('dob'),
					'photo' => $this->input->post('photo'),
					'company' => $this->input->post('company'),
					'phone' => $this->input->post('phone'),
					'job_describtion' => $this->input->post('job_describtion'),
                );

                $this->User_model->update_user($id,$params);            
                redirect('user/index');
            }
            else
            {
                $data['_view'] = 'user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
    } 

    /*
     * Deleting user
     */
    function remove($id)
    {
        $user = $this->User_model->get_user($id);

        // check if the user exists before trying to delete it
        if(isset($user['id']))
        {
            $this->User_model->delete_user($id);
            redirect('user/index');
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }
    
}
