<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Assignment_model extends CI_Model
{

    public $table = 'assignment';
    public $id = 'id';
    public $user_id = 'user_id';
    public $stage_id = 'stage_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
	}
	

	function get_by_user_and_stage($user_id, $stage_id){
		$this->db->where($this->user_id, $user_id);
		$this->db->where($this->stage_id, $stage_id);
        return $this->db->get($this->table)->result();
	}
    
    
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Assignment_model.php */
/* Location: ./application/models/Assignment_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-09 23:49:14 */
/* http://harviacode.com */
