<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stage_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get stage by id
     */
    function get_stage($id)
    {
        return $this->db->get_where('stages',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all stages
     */
    function get_all_stages()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('stages')->result_array();
    }
        
    /*
     * function to add new stage
     */
    function add_stage($params)
    {
        $this->db->insert('stages',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update stage
     */
    function update_stage($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('stages',$params);
    }
    
    /*
     * function to delete stage
     */
    function delete_stage($id)
    {
        return $this->db->delete('stages',array('id'=>$id));
    }
}
